[0m00:42:31.006589 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ffedb197010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ffedb16a8d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ffedb5f1210>]}


============================== 00:42:31.010440 | 6dcdc56a-087c-4469-bef6-b0402c65c870 ==============================
[0m00:42:31.010440 [info ] [MainThread]: Running with dbt=1.10.13
[0m00:42:31.011140 [debug] [MainThread]: running dbt with arguments {'log_format': 'default', 'version_check': 'True', 'target_path': 'None', 'use_colors': 'True', 'indirect_selection': 'eager', 'invocation_command': 'dbt init', 'no_print': 'None', 'fail_fast': 'False', 'warn_error': 'None', 'quiet': 'False', 'cache_selected_only': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'profiles_dir': '/home/michielsmulders/.dbt', 'send_anonymous_usage_stats': 'True', 'log_path': 'logs', 'use_experimental_parser': 'False', 'printer_width': '80', 'empty': 'None', 'introspect': 'True', 'debug': 'False', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'static_parser': 'True'}
[0m00:42:31.019015 [info ] [MainThread]: Creating dbt configuration folder at /home/michielsmulders/.dbt
[0m00:43:13.300183 [debug] [MainThread]: Starter project path: /home/michielsmulders/git-projects/r-wallstreetbots/dbt-core-venv/lib/python3.11/site-packages/dbt/include/starter_project
[0m00:43:13.303696 [info ] [MainThread]: 
Your new dbt project "wallstreet_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m00:43:13.304551 [info ] [MainThread]: Setting up your profile.
[0m00:43:43.609438 [error] [MainThread]: Encountered an error:

[0m00:43:43.612575 [error] [MainThread]: Traceback (most recent call last):
  File "/home/michielsmulders/git-projects/r-wallstreetbots/dbt-core-venv/lib/python3.11/site-packages/dbt/cli/requires.py", line 178, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/michielsmulders/git-projects/r-wallstreetbots/dbt-core-venv/lib/python3.11/site-packages/dbt/cli/requires.py", line 128, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/michielsmulders/git-projects/r-wallstreetbots/dbt-core-venv/lib/python3.11/site-packages/dbt/cli/main.py", line 483, in init
    results = task.run()
              ^^^^^^^^^^
  File "/home/michielsmulders/git-projects/r-wallstreetbots/dbt-core-venv/lib/python3.11/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/home/michielsmulders/git-projects/r-wallstreetbots/dbt-core-venv/lib/python3.11/site-packages/dbt/task/init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "/home/michielsmulders/git-projects/r-wallstreetbots/dbt-core-venv/lib/python3.11/site-packages/dbt/task/init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "/home/michielsmulders/git-projects/r-wallstreetbots/dbt-core-venv/lib/python3.11/site-packages/dbt/task/init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michielsmulders/git-projects/r-wallstreetbots/dbt-core-venv/lib/python3.11/site-packages/dbt/task/init.py", line 129, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "/home/michielsmulders/git-projects/r-wallstreetbots/dbt-core-venv/lib/python3.11/site-packages/click/termui.py", line 168, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/michielsmulders/git-projects/r-wallstreetbots/dbt-core-venv/lib/python3.11/site-packages/click/termui.py", line 151, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m00:43:43.614527 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 72.66218, "process_in_blocks": "0", "process_kernel_time": 0.128106, "process_mem_max_rss": "104320", "process_out_blocks": "320", "process_user_time": 1.473228}
[0m00:43:43.615329 [debug] [MainThread]: Command `dbt init` failed at 00:43:43.615155 after 72.66 seconds
[0m00:43:43.615904 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ffedf84ae90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ffedb136810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ffedb12b990>]}
[0m00:43:43.616504 [debug] [MainThread]: Flushing usage events
[0m00:43:44.073037 [debug] [MainThread]: An error was encountered while trying to flush usage events
